### ISSUE TITLE
Incorrect package description

### ISSUE THREAD

**Issue by jpvillaisaza** [collegevine/purescript-intertwine#1]
It looks like the description of the package is currently the description of a different package:

https://github.com/collegevine/purescript-intertwine/blob/f4b31f736ffc692170d6b97673ff121eac246727/bower.json#L3

Should it be something like "Reversible printing/parsing" or "Invertible syntax descriptions"?

**Comment by fsoikin** [comment]
Oh no! How could I have messed that up?! 
Thank you for noticing :-)

**Comment by fsoikin** [comment]
Fixed in https://github.com/collegevine/purescript-intertwine/commit/2362f3b7c2fde110b609243035f174fe089e51d2
